### ISSUE TITLE
Code review Devgym 🎉 

### ISSUE THREAD

**Issue by filhodanuvem** [julianojj/desafio_encurtador_url#1]
Fala @julianojj , primeiro parabéns por ter completado o desafio. Foi bem rápido nesse, vou ter que criar uns mais desafiadores pra você haha. 
Alguns comentários : 

### Experiência do usuário
* Já que o `.db.env` é obrigatório, você poderia ou ter ele no repositorio com valores vazios para env vars necessárias ou ter um `.db.env.example` e sugerir a pessoa de renomear o arquivo. 
* voce commitou um usuário e senha padrao no arquivo go, voce poderia ter usado o pacote `os` com a função [os.getenv](https://pkg.go.dev/os#Getenv) para utilizar as mesmas env vars. Outra opção é usar o projeto [dotenv](https://github.com/joho/godotenv) que possibilita ler um arquivo .env. 
* é possivel também ja subir o banco de dados com tabelas e dados que você queira. Você pode dar olhada em como montar um volume dentro do container docker que aponta pra um arquivo que voce tem no seu projeto. O arquivo vai ter qualquer sql e o banco vai executar o arquivo assim que subir. [Exemplo](https://gist.github.com/onjin/2dd3cc52ef79069de1faa2dfd456c945#file-docker-compose-yml-L4). 

### Design

* Achei muito legal que você brincou com duas implementações de repository 👍🏾 
* Se nao me engano ` time.Now().AddDate(0, 0, 1)` pode ser escrito de forma mais facil de ler como `time.Now().Add(24 * time.Hour)`[aqui](https://github.com/julianojj/desafio_encurtador_url/blob/main/internal/usecases/make_shortener_url.go#LL30C25-L30C42) , mas é um detalhe. 
* Achei legal que você pensou na expiração do link 
* os testes precisavam ser mais flexiveis para nao obrigar a conexao do banco[ aqui](https://github.com/julianojj/desafio_encurtador_url/blob/main/internal/usecases/make_shortener_url_test.go#L14) esperando env vars tambem. 
* É muito importante pensar em testes pelo lado negativo, os unhappy tests. Você [está](https://github.com/julianojj/desafio_encurtador_url/blob/main/internal/usecases/make_shortener_url_test.go#L13) garantindo que uma url é salva no banco mas quais são os cenários de erros? Salvar a mesma url duas vezes gera hashes diferentes obrigatoriamente? Simular que o banco esta fora do ar retorna um erro? 
* legal que voce pensou nos [status codes](https://github.com/julianojj/desafio_encurtador_url/blob/main/internal/infra/api/controllers/shortener_controller.go#L22) dos endpoints.  🎖️ 
* O endpoint que busca a url deveria retornar 404 em alguns casos, penso eu, mas pelo o que vejo ou retorna um sucesso ou um internal server error. É importante se atentar que errors 5xx dizem pro usuário que o problema está no servidor e se ele tentar novamente pode ser que a resposta mude. O que não necessariamente é verdade no caso das urls expiradas ou hashes não encontradas.

De novo meus parabéns pela solução, gostei também da organização de código e deu pra ver que você usou diferentes conceitos. 
Posso em algum momento fazer um vídeo no canal com sua solução?

**Comment by julianojj** [comment]
Tudo bem Claudson?
Vi aqui as sugestões de mudanças, fiz meio na correra a questão de os env, mas irei aderir a mudança
Referente ao testes, foi implementado testes de unidade e de integração,
No banco de dados, há um repository em memory, porém esqueci de altera-lo no teste rs.
Pode fazer um vídeo sim com a solução :)

**Comment by julianojj** [comment]
Tudo bem Claudson?
Muito bom o review, fiz algumas mudanças de acordo com o que tu sugeriu,
Referênte a estrutura estou utilizando uma baseada na clean architecture, onde visa o desacoplamento da aplicação, e está me ajudando muito.
Pode fazer o vídeo sim. Vai ajudar mais ainda a galera a prender sobre Go :)
